<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="base_length" value="0.25" />
    <xacro:property name="base_width" value="0.25" />
    <xacro:property name="base_wheel_x" value="-0.087" />
    <xacro:property name="base_wheel_x_front" value="0.07" />
    <xacro:property name="base_wheel_y" value="0.15" />
    <xacro:property name="base_wheel_z" value="-0.002" />
    <xacro:property name="base_height" value="0.3" />
    <xacro:property name="wheel_radius" value="0.05" />
    <xacro:property name="wheel_length" value="0.03" />

    <link name="base_footprint" />

    <link name="base_link">
        <visual>
            <geometry>
                <!-- <box size="${base_length} ${base_width} ${base_height}" /> -->
                <mesh filename="package://kpbot_description/models/meshes/composite_part_1.stl"/>

            </geometry>
            <origin xyz="0.1 0.05 -0.1" rpy="1.57 0 -1.57" />
            <material name="pink" />
        </visual>
        <collision>
            <geometry>
                <box size="${base_length} ${base_width} ${base_height}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <xacro:box_inertia m="5.0" l="${2*base_length}" w="${base_width}" h="${base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
    </link>

    <xacro:macro name="wheel_link" params="prefix">
        
    </xacro:macro>

    <xacro:wheel_link prefix="back_right" />
    <!-- <xacro:wheel_link prefix="back_left" />
    <xacro:wheel_link prefix="front_right" />
    <xacro:wheel_link prefix="front_left" /> -->

    <link name="back_right_wheel_link">
        <visual>
            <geometry>
                <!-- <cylinder radius="${wheel_radius}" length="${wheel_length}" /> -->
                <mesh filename="package://kpbot_description/models/meshes/wheel.stl"/>
            </geometry>
            <!-- <origin xyz="0.01 -0.054 -0.033" rpy="0 0 ${pi / 2.0}" /> -->
                <origin xyz="0 0 0" rpy="0 0 -1.57" />

            <material name="violet" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="${base_wheel_x} ${base_wheel_y} ${base_wheel_z}" rpy="-1.57 0 1.57" />
        </collision>
        <xacro:cylinder_inertia m="2.0" r="${wheel_radius}" h="${wheel_length}" 
                                xyz="0 0 0" rpy="0 0 1.57" />
    </link>

    <link name="front_right_wheel_link">
        <visual>
            <geometry>
                <!-- <cylinder radius="${wheel_radius}" length="${wheel_length}" /> -->
                <mesh filename="package://kpbot_description/models/meshes/wheel.stl"/>
            </geometry>
            <!-- <origin xyz="0.01 -0.054 -0.033" rpy="0 0 0" /> -->
                <origin xyz="0 0 0" rpy="0 0 -1.57" />

            <material name="violet" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="${base_wheel_x_front} ${base_wheel_y} ${base_wheel_z}" rpy="-1.57 0 1.57" />
        </collision>
        <xacro:cylinder_inertia m="2.0" r="${wheel_radius}" h="${wheel_length}" 
                                xyz="0 0 0" rpy="0 0 1.57" />
    </link>

    <link name="back_left_wheel_link">
        <visual>
            <geometry>
                <!-- <cylinder radius="${wheel_radius}" length="${wheel_length}" /> -->
                <mesh filename="package://kpbot_description/models/meshes/wheel.stl"/>
            </geometry>
            <!-- <origin xyz="0.01 -0.054 -0.033" rpy="0 0 0" /> -->
                <origin xyz="0 0 0" rpy="0 0 1.57" />

            <material name="violet" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="${base_wheel_x} ${0.009-base_wheel_y} ${base_wheel_z}" rpy="1.57 0 1.57" />
        </collision>
        <xacro:cylinder_inertia m="2.0" r="${wheel_radius}" h="${wheel_length}" 
                                xyz="0 0 0" rpy="0 0 1.57" />
    </link>

    <link name="front_left_wheel_link">
        <visual>
            <geometry>
                <!-- <cylinder radius="${wheel_radius}" length="${wheel_length}" /> -->
                <mesh filename="package://kpbot_description/models/meshes/wheel.stl"/>
            </geometry>
            <!-- <origin xyz="0.01 -0.054 -0.033" rpy="0 0 0" /> -->
                <origin xyz="0 0 0" rpy="0 0 1.57" />

            <material name="violet" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}" />
            </geometry>
            <origin xyz="${base_wheel_x_front} ${0.009-base_wheel_y} ${base_wheel_z}" rpy="1.57 0 1.57" />
        </collision>
        <xacro:cylinder_inertia m="2.0" r="${wheel_radius}" h="${wheel_length}" 
                                xyz="0 0 0" rpy="0 0 1.57" />
    </link>

    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 0.02" rpy="0 0 0"/>
    </joint>

    <joint name="back_right_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_right_wheel_link" />
        <origin xyz="${base_wheel_x} ${base_wheel_y} ${base_wheel_z}" rpy="0.0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="front_right_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_right_wheel_link" />
        <origin xyz="${base_wheel_x_front} ${base_wheel_y} ${base_wheel_z}" rpy="0.0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="back_left_joint" type="continuous">
        <parent link="base_link" />
        <child link="back_left_wheel_link" />
        <origin xyz="${base_wheel_x} ${0.009-base_wheel_y} ${base_wheel_z}" rpy="0 0 0" />
        <axis xyz="0 1 0" />
    </joint>

    <joint name="front_left_joint" type="continuous">
        <parent link="base_link" />
        <child link="front_left_wheel_link" />
        <origin xyz="${base_wheel_x_front} ${0.009-base_wheel_y} ${base_wheel_z}" rpy="0 0 0.0" />
        <axis xyz="0 1 0" />
    </joint>

</robot>